name: signalbyt
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.15+15

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.1.3
  firebase_core: ^2.3.0
  cloud_firestore: ^4.1.0
  firebase_storage: ^11.0.6
  firebase_messaging: ^14.1.1
  firebase_analytics: ^10.0.6
  firebase_crashlytics: ^3.0.6
  flutter_local_notifications: ^14.1.1
  provider: ^6.0.2
  path_provider: ^2.0.2
  hive: ^2.0.4
  get: ^4.6.5
  dio: ^5.0.0
  flutter_spinkit: ^5.1.0
  loading_animations: ^2.2.0
  modal_bottom_sheet: ^2.0.1
  google_sign_in: ^6.0.1
  sign_in_with_apple: ^5.0.0
  package_info: ^2.0.0
  flutter_animated_dialog: ^2.0.1
  flutter_styled_toast: ^2.1.3
  url_launcher: ^6.1.4
  uuid: ^3.0.4
  shimmer: ^3.0.0
  configurable_expansion_tile_null_safety: ^3.1.1
  introduction_screen: ^3.0.0
  json_annotation: ^4.0.0
  flutter_icons:
    git:
      url: https://github.com/adarsh-technocrat/flutter-icons.git
      branch: null-safety-migration
  dotted_border: ^2.0.0+1
  share_plus: ^7.0.2
  hexcolor: ^3.0.1
  purchases_flutter: ^5.2.3
  # in_app_purchase: ^3.0.4
  carousel_slider: ^4.0.0
  pull_to_refresh: ^2.0.0
  image_picker: ^1.0.0
  youtube_player_iframe: ^4.0.4
  youtube_parser: ^2.0.0
  smooth_star_rating_null_safety: ^1.0.4+2
  blurrycontainer: ^1.0.2
  toggle_switch: ^2.0.1
  cached_network_image: ^3.2.0
  image_cropper: ^4.0.1
  flutter_image_compress: ^2.0.3
  change_case: ^1.0.2
  timeago_flutter: ^3.4.0
  flutter_native_splash: ^2.2.16
  easy_localization: ^3.0.1
  flutter_dotenv: ^5.0.2
  flutter_widget_from_html_core: ^0.10.0
  fwfh_webview: ^0.7.0+1
  webview_flutter: ^4.0.5
  flutter_widget_from_html: ^0.10.0
  flutter_svg: ^2.0.2
  google_fonts: ^4.0.3
  socket_io_client: ^2.0.0
  custom_navigation_bar: ^0.8.2
  html: ^0.15.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.4
  build_runner: ^2.0.4
  #flutter packages pub run flutter_launcher_icons:main
  flutter_launcher_icons: ^0.13.1
flutter_icons:
  image_path: "assets/icon/icon.png"
  android: true
  remove_alpha_ios: true
  ios: true


flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/svg/
    - assets/translations/
